[package]
name = "halo2-ops"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
halo2_proofs = "0.2"
halo2_gadgets = "0.2.0"
ff = "0.12"
pasta_curves = "0.4"